package com.chasmet.modeliseur3d.model;
import java.util.ArrayList;
final class DepthV74Ray{
 static final class S{final int a,b;final float lo,hi,cl,ch;final boolean vl,vh;S(int a,int b,float lo,float hi,float cl,float ch,boolean vl,boolean vh){this.a=a;this.b=b;this.lo=lo;this.hi=hi;this.cl=cl;this.ch=ch;this.vl=vl;this.vh=vh;}}
 final S[] s;final double shift;final int moved;DepthV74Ray(S[] s,double shift,int moved){this.s=s;this.shift=shift;this.moved=moved;}
 static DepthV74Ray z(float[] v,int w,int d,int y,int x,DepthV74View low,int li,DepthV74View high,int hi,float inset,float gap){ArrayList<int[]> a=new ArrayList<>();int z=0;while(z<d){while(z<d&&v[idx(x,y,z,w,d)]<.5f)z++;if(z>=d)break;int p=z;while(z+1<d&&v[idx(x,y,z+1,w,d)]>=.5f)z++;a.add(new int[]{p,z});z++;}return make(a,low,li,high,hi,inset,gap);}
 static DepthV74Ray x(float[] v,int w,int d,int y,int z,DepthV74View low,int li,DepthV74View high,int hi,float inset,float gap){ArrayList<int[]> a=new ArrayList<>();int x=0;while(x<w){while(x<w&&v[idx(x,y,z,w,d)]<.5f)x++;if(x>=w)break;int p=x;while(x+1<w&&v[idx(x+1,y,z,w,d)]>=.5f)x++;a.add(new int[]{p,x});x++;}return make(a,low,li,high,hi,inset,gap);}
 private static DepthV74Ray make(ArrayList<int[]> a,DepthV74View l,int li,DepthV74View h,int hi,float f,float gap){S[] out=new S[a.size()];double sh=0;int mv=0;for(int i=0;i<a.size();i++){int mn=a.get(i)[0],mx=a.get(i)[1];float span=Math.max(1,mx-mn),cap=Math.max(.32f,span*f);boolean vl=(a.size()==1||i==0)&&l.valid&&l.usable(li),vh=(a.size()==1||i==a.size()-1)&&h.valid&&h.usable(hi);float il=vl?l.inset(li,cap):0,ih=vh?h.inset(hi,cap):0,lo=mn+il,high=mx-ih,g=Math.min(Math.max(.62f,span*gap),Math.max(.62f,span));if(high-lo<g){float c=(lo+high)*.5f;lo=c-g*.5f;high=c+g*.5f;}lo=Math.max(mn,Math.min(mx,lo));high=Math.max(mn,Math.min(mx,high));out[i]=new S(mn,mx,lo,high,l.conf(li),h.conf(hi),vl,vh);sh+=il+ih;if(il>.05)mv++;if(ih>.05)mv++;}return new DepthV74Ray(out,sh,mv);}
 float[] support(int p){for(S q:s)if(p>=q.a&&p<=q.b){if(!q.vl&&!q.vh)return null;float a=q.vl?smooth(q.lo-.82f,q.lo+.82f,p):1,b=q.vh?1-smooth(q.hi-.82f,q.hi+.82f,p):1,c=q.vl&&q.vh?(q.cl+q.ch)*.5f:q.vl?q.cl:q.ch;return new float[]{Math.min(a,b),c};}return null;}
 private static float smooth(float a,float b,float x){float t=Math.max(0,Math.min(1,(x-a)/Math.max(.0001f,b-a)));return t*t*(3-2*t);}private static int idx(int x,int y,int z,int w,int d){return(y*w+x)*d+z;}
}
