package com.chasmet.modeliseur3d.model;
final class DepthV74Engine{
 static MultiViewDepthFusion.Result run(float[] base,boolean[][] m,float[][] rd,float[][] rc,int w,int h,int d,SubjectCategory cat){
  check(base,m,rd,rc,w,h,d);if(cat==null||cat==SubjectCategory.AUTO)cat=SubjectCategory.CHARACTER;DepthFusionPolicy pol=DepthFusionPolicy.forCategory(cat);DepthV74Shape sh=DepthV74Shape.make(m,w,h,d);int[] vw={w,d,w,d};DepthV74View[] v=new DepthV74View[4];int good=0;for(int i=0;i<4;i++){v[i]=DepthV74View.make(rd[i],rc[i],m[i]);if(v[i].valid)good++;}if(good<2)return MultiViewDepthFusion.Result.unchanged(base,good,"profondeur DA3 plate ou insuffisante "+good+"/4");
  DepthV74Gate gate=DepthV74Gate.make(m,w,h,d,cat);DepthV74Ray[] zr=new DepthV74Ray[w*h],xr=new DepthV74Ray[d*h];double shift=0;int moved=0;
  for(int y=0;y<h;y++){DepthFusionPolicy.Zone z=pol.zone(sh.p(y),sh.fr[y],sh.sr[y],sh.ff[y],sh.sf[y]);for(int x=0;x<w;x++){int a=y*w+x,b=y*w+w-1-x;DepthV74Ray q=DepthV74Ray.z(base,w,d,y,x,v[0],a,v[2],b,z.maximumInsetFraction,z.minimumGapFraction);zr[a]=q;shift+=q.shift;moved+=q.moved;}for(int p=0;p<d;p++){int a=y*d+p,b=y*d+d-1-p;DepthV74Ray q=DepthV74Ray.x(base,w,d,y,p,v[3],b,v[1],a,z.maximumInsetFraction*z.crossAxisScale,z.minimumGapFraction);xr[a]=q;shift+=q.shift;moved+=q.moved;}}
  float[] out=new float[base.length];int bo=0,oo=0,ch=0,pruned=0;
  for(int y=0;y<h;y++){DepthFusionPolicy.Zone z=pol.zone(sh.p(y),sh.fr[y],sh.sr[y],sh.ff[y],sh.sf[y]);DepthV74Gate.Row g=gate.rows[y];for(int x=0;x<w;x++){for(int p=0;p<d;p++){int i=idx(x,y,p,w,d);float b=base[i];if(b>=.5f)bo++;if(b<=0||edge(x,y,p,w,h,d)){out[i]=0;continue;}if(!g.ok(x,p)){out[i]=0;if(b>=.5f)pruned++;if(b>.08f)ch++;continue;}float[] a=zr[y*w+x].support(p),c=xr[y*d+p].support(x);if(a==null&&c==null){out[i]=b;if(b>=.5f)oo++;continue;}float sup,cf;if(a!=null&&c!=null){float lo=Math.min(a[0],c[0]),hi=Math.max(a[0],c[0]);sup=lo*(1-z.ambiguityProtection)+hi*z.ambiguityProtection;cf=(a[1]+c[1])*.5f;}else{float[] q=a!=null?a:c;sup=q[0];cf=q[1];}float inf=z.minimumInfluence+z.confidenceInfluence*clamp(cf);float val=b*(1-inf+inf*sup);if(z.coreRadius>.001f){float nx=Math.abs(x-sh.cx[y])/Math.max(1,sh.hx[y]),nz=Math.abs(p-sh.cz[y])/Math.max(1,sh.hz[y]),cd=Math.max(nx,nz);if(cd<=z.coreRadius){float cw=1-smooth(z.coreRadius*.55f,z.coreRadius,cd);val=Math.max(val,b*z.coreFloor*cw);}}out[i]=clamp(val);if(Math.abs(out[i]-b)>.08f)ch++;if(out[i]>=.5f)oo++;}}}
  boolean guard=bo>0&&oo<Math.round(bo*pol.minimumRetainedFraction);if(guard){oo=0;ch=0;for(int y=0;y<h;y++){DepthV74Gate.Row g=gate.rows[y];for(int x=0;x<w;x++)for(int p=0;p<d;p++){int i=idx(x,y,p,w,d);if(base[i]<=0||!g.ok(x,p)||edge(x,y,p,w,h,d)){out[i]=0;continue;}out[i]=clamp(base[i]*pol.collapseBaseWeight+out[i]*(1-pol.collapseBaseWeight));if(Math.abs(out[i]-base[i])>.08f)ch++;if(out[i]>=.5f)oo++;}}}
  if(ch<Math.max(12,base.length/240000))return MultiViewDepthFusion.Result.unchanged(base,good,"relief DA3 trop faible ("+ch+" voxels)");return new MultiViewDepthFusion.Result(out,true,good,ch,oo,moved==0?0:shift/moved,guard,pruned,"fusion DA3 multi-experts par correspondance 3D de composantes appliquée");
 }
 private static void check(float[] b,boolean[][] m,float[][] d,float[][] c,int w,int h,int z){if(w<4||h<4||z<4||b==null||b.length!=w*h*z||m==null||m.length!=4||d==null||d.length!=4||c==null||c.length!=4)throw new IllegalArgumentException("Fusion DA3 multivue invalide");int[] q={w,z,w,z};for(int i=0;i<4;i++){int n=q[i]*h;if(m[i]==null||m[i].length!=n||d[i]==null||d[i].length!=n||c[i]==null||c[i].length!=n)throw new IllegalArgumentException("Carte DA3 "+i+" invalide");}}
 private static boolean edge(int x,int y,int z,int w,int h,int d){return x==0||y==0||z==0||x==w-1||y==h-1||z==d-1;}private static int idx(int x,int y,int z,int w,int d){return(y*w+x)*d+z;}private static float clamp(float v){return Math.max(0,Math.min(1,v));}private static float smooth(float a,float b,float v){float t=clamp((v-a)/Math.max(.0001f,b-a));return t*t*(3-2*t);}
}
